### ISSUE TITLE
[Bug]: No skip button or autoskip

### ISSUE THREAD

**Issue by truthsword** [jumoog/intro-skipper#198]
### Self service debugging

- [X] Jellyfin is updated and my permissions are correct (or I did not use Docker)

### Describe the bug

Running docker container v10.9.6. Issued `chown 1000 /usr/share/jellyfin/web/index.html` but no change. Sorta of lost where to turn. Logs appear to show all scans complete. See this though...

`[ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.`

```
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    security_opt:
      - no-new-privileges=true
    devices:
      - /dev/dri:/dev/dri
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    network_mode: bridge
    ports:
      - "8096:8096"
    volumes:
      - config:/config
      - /mnt/plex/media/tv_shows:/data/tvshows
      - /mnt/plex/media/movies:/data/movies

volumes:
  config:
```

### Jellyfin install method

Docker

### Container image/tag or Jellyfin version

10.9.6

### Operating System

Debian 12

### IMDb ID of that TV Series

tt0096697

### Support Bundle

```shell
* Jellyfin version: 10.9.6
* Plugin version: 0.2.0+ddd538c29675
* Queue contents: 5979 episodes, 436 seasons
* Warnings: `UnableToAddSkipButton, InvalidChromaprintFingerprint`
* FFmpeg: `okay`

FFmpeg version:

ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.4.0-1ubuntu1~22.04)
configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=amd64 --enable-libshaderc --enable-libplacebo --enable-vulkan --enable-vaapi --enable-amf --enable-libvpl --enable-ffnvcodec --enable-cuda --enable-cuda-llvm --enable-cuvid --enable-nvdec --enable-nvenc
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
libpostproc    57.  1.100 / 57.  1.100
```

### Jellyfin logs

```shell
[ERR] [1] ConfusedPolarBear.Plugin.IntroSkipper.Plugin: Failed to add skip button to web interface. Try running `sudo chown jellyfin /usr/share/jellyfin/web/index.html` (if this is a native installation) and restarting the server. Error: System.UnauthorizedAccessException: Access to the path '/usr/share/jellyfin/web/index.html' is denied.
```
